stages:
  - test

testJob:
  stage: test
  environment:
    name: testing
  when: manual
  tags:
    # Want cvmfs mounted for TeXLive
    - cvmfs
  
  variables:
    # example
    CMS_LOCAL_ROOT_BASE: /cvmfs/cms.cern.ch/
    GIT_SUBMODULE_STRATEGY: recursive
  
  script:
    - mkdir output
    - pwd
    - perl utils/tdr --style note  --temp_dir=output b 
  artifacts:
    paths:
      - output

buildJob:
  stage: test
  environment:
    name: building
  when: manual
  tags:
    # Want cvmfs mounted for TeXLive
    - cvmfs
  
  variables:
    # example
    CMS_LOCAL_ROOT_BASE: /cvmfs/cms.cern.ch/
    GIT_SUBMODULE_STRATEGY: recursive
  
  script:
    - yum install -y -q perl-libwww-perl perl-IO-Socket-SSL perl-XML-Twig ImageMagick
    - mkdir output
    - pwd
    - perl utils/tdr --style note --verbose --preview --temp_dir=output b 
  artifacts:
    paths:
      - output